chore(main): remove the deprecated function matchersWithFormats
americanexpress/jest-json-schema pull request #23
Opened 2020-10-24 21:31 UTC by realityking

If #22 is merged and a major release done, this would also be an opportunity to remove the long-deprecated `matchersWithFormats `

2020-11-24 14:03 UTC, realityking commented
PR is still relevant/waiting for feedback.

2020-12-03 21:43 UTC, PixnBits approved these changes

2020-12-03 21:44 UTC, PixnBits requested changes
actually, sorry
we need to indicate that this is a breaking change, so need a line in the commit message "body" https://www.conventionalcommits.org/en/v1.0.0/#commit-message-with-description-and-breaking-change-footer

Thank you so much for your contributions on this!

2020-12-03 22:12 UTC, 10xLaCroixDrinker approved these changes

2020-12-03 22:20 UTC, realityking commented
@PixnBits I pushed a commit with the `BREAKING CHANGE:` in the commit :)

2020-12-03 23:28 UTC, PixnBits approved these changes

2020-12-15 21:17 UTC, 10xLaCroixDrinker approved these changes

2021-01-15 14:35 UTC, nellyk approved these changes

2021-01-19 10:42 UTC, merged